version: "3.8"

services:
  recipes_database:
    container_name: recipes-database
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recipes_database
    ports:
      - "5432:5432"
    networks:
      - recipes-network

  recipes_api:
    container_name: recipes-api
    build:
      context: ./back-end
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - PORT=80
      - RECIPES_DATABASE_USER=postgres
      - RECIPES_DATABASE_PASSWORD=postgres
      - RECIPES_DATABASE_PORT=5432
      - RECIPES_DATABASE_HOST=recipes_database
    ports:
      - "80:80"
    depends_on:
      - recipes_database
    networks:
      - recipes-network

  recipes_client:
    container_name: recipes-client
    build:
      context: ./front-end
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "3000:3000"

networks:
  recipes-network:



